# Generated by Django 3.2.19 on 2023-06-13 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_bikes_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
