# Generated by Django 3.2.19 on 2023-06-14 16:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_bikes_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='image',
            field=cloudinary.models.CloudinaryField(default='no_image.jpg', max_length=255, verbose_name='image'),
        ),
    ]
