# Generated by Django 3.2.19 on 2023-06-14 17:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bikes_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
