# Generated by Django 3.2.19 on 2023-06-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_bikes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=8),
        ),
    ]
