# Generated by Django 3.2.19 on 2023-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_bikes_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikes',
            name='seat_height',
            field=models.DecimalField(decimal_places=2, default=90, max_digits=8),
        ),
        migrations.AddField(
            model_name='bikes',
            name='starter',
            field=models.CharField(default='Kick', max_length=50),
        ),
    ]
